iconv -f GB2312 -t UTF-8 ./.gitignore                         -o ../SmartHomeUtf/.gitignore
iconv -f GB2312 -t UTF-8 ./debug/debug_init.c                 -o ../SmartHomeUtf/debug/debug_init.c
iconv -f GB2312 -t UTF-8 ./debug/errlog.c                     -o ../SmartHomeUtf/debug/errlog.c
iconv -f GB2312 -t UTF-8 ./debug/ethshell.c                   -o ../SmartHomeUtf/debug/ethshell.c
iconv -f GB2312 -t UTF-8 ./debug/log.c                        -o ../SmartHomeUtf/debug/log.c
iconv -f GB2312 -t UTF-8 ./debug/Makefile                     -o ../SmartHomeUtf/debug/Makefile
iconv -f GB2312 -t UTF-8 ./debug/pipeshell.c                  -o ../SmartHomeUtf/debug/pipeshell.c
iconv -f GB2312 -t UTF-8 ./debug/shell.c                      -o ../SmartHomeUtf/debug/shell.c
iconv -f GB2312 -t UTF-8 ./debug/shell.h                      -o ../SmartHomeUtf/debug/shell.h
iconv -f GB2312 -t UTF-8 ./debug/shellcmd.c                   -o ../SmartHomeUtf/debug/shellcmd.c
iconv -f GB2312 -t UTF-8 ./debug/statistic.c                  -o ../SmartHomeUtf/debug/statistic.c
iconv -f GB2312 -t UTF-8 ./debug/svrcomm_shell.c              -o ../SmartHomeUtf/debug/svrcomm_shell.c
iconv -f GB2312 -t UTF-8 ./debug/ttyshell.c                   -o ../SmartHomeUtf/debug/ttyshell.c
iconv -f GB2312 -t UTF-8 ./downlink/dbclear.c                 -o ../SmartHomeUtf/downlink/dbclear.c
iconv -f GB2312 -t UTF-8 ./downlink/downlink645.c             -o ../SmartHomeUtf/downlink/downlink645.c
iconv -f GB2312 -t UTF-8 ./downlink/downlink645.h             -o ../SmartHomeUtf/downlink/downlink645.h
iconv -f GB2312 -t UTF-8 ./downlink/downlink_buffer.c         -o ../SmartHomeUtf/downlink/downlink_buffer.c
iconv -f GB2312 -t UTF-8 ./downlink/downlink_dl.c             -o ../SmartHomeUtf/downlink/downlink_dl.c
iconv -f GB2312 -t UTF-8 ./downlink/downlink_dl.h             -o ../SmartHomeUtf/downlink/downlink_dl.h
iconv -f GB2312 -t UTF-8 ./downlink/Makefile                  -o ../SmartHomeUtf/downlink/Makefile
iconv -f GB2312 -t UTF-8 ./downlink/module/Makefile           -o ../SmartHomeUtf/downlink/module/Makefile
iconv -f GB2312 -t UTF-8 ./downlink/module/rfmet.c            -o ../SmartHomeUtf/downlink/module/rfmet.c
iconv -f GB2312 -t UTF-8 ./downlink/module/rfmet.h            -o ../SmartHomeUtf/downlink/module/rfmet.h
iconv -f GB2312 -t UTF-8 ./downlink/plcomm.c                  -o ../SmartHomeUtf/downlink/plcomm.c
iconv -f GB2312 -t UTF-8 ./downlink/plcomm.h                  -o ../SmartHomeUtf/downlink/plcomm.h
iconv -f GB2312 -t UTF-8 ./downlink/plmdb.c                   -o ../SmartHomeUtf/downlink/plmdb.c
iconv -f GB2312 -t UTF-8 ./downlink/plmdb.h                   -o ../SmartHomeUtf/downlink/plmdb.h
iconv -f GB2312 -t UTF-8 ./downlink/pltask.c                  -o ../SmartHomeUtf/downlink/pltask.c
iconv -f GB2312 -t UTF-8 ./downlink/qrcode.c                  -o ../SmartHomeUtf/downlink/qrcode.c
iconv -f GB2312 -t UTF-8 ./downlink/qrcode.h                  -o ../SmartHomeUtf/downlink/qrcode.h
iconv -f GB2312 -t UTF-8 ./ftp_up.sh                          -o ../SmartHomeUtf/ftp_up.sh
iconv -f GB2312 -t UTF-8 ./include/basetype.h                 -o ../SmartHomeUtf/include/basetype.h
iconv -f GB2312 -t UTF-8 ./include/debug/shellcmd.h           -o ../SmartHomeUtf/include/debug/shellcmd.h
iconv -f GB2312 -t UTF-8 ./include/debug/statistic.h          -o ../SmartHomeUtf/include/debug/statistic.h
iconv -f GB2312 -t UTF-8 ./include/debug/svrcomm_shell.h      -o ../SmartHomeUtf/include/debug/svrcomm_shell.h
iconv -f GB2312 -t UTF-8 ./include/debug.h                    -o ../SmartHomeUtf/include/debug.h
iconv -f GB2312 -t UTF-8 ./include/environment.h              -o ../SmartHomeUtf/include/environment.h
iconv -f GB2312 -t UTF-8 ./include/lib/align.h                -o ../SmartHomeUtf/include/lib/align.h
iconv -f GB2312 -t UTF-8 ./include/lib/bcd.h                  -o ../SmartHomeUtf/include/lib/bcd.h
iconv -f GB2312 -t UTF-8 ./include/lib/crc.h                  -o ../SmartHomeUtf/include/lib/crc.h
iconv -f GB2312 -t UTF-8 ./include/lib/datachg.h              -o ../SmartHomeUtf/include/lib/datachg.h
iconv -f GB2312 -t UTF-8 ./include/lib/datatype_gb.h          -o ../SmartHomeUtf/include/lib/datatype_gb.h
iconv -f GB2312 -t UTF-8 ./include/lib/dbtime.h               -o ../SmartHomeUtf/include/lib/dbtime.h
iconv -f GB2312 -t UTF-8 ./include/monitor/alarm.h            -o ../SmartHomeUtf/include/monitor/alarm.h
iconv -f GB2312 -t UTF-8 ./include/monitor/runstate.h         -o ../SmartHomeUtf/include/monitor/runstate.h
iconv -f GB2312 -t UTF-8 ./include/param/capconf.h            -o ../SmartHomeUtf/include/param/capconf.h
iconv -f GB2312 -t UTF-8 ./include/param/commport.h           -o ../SmartHomeUtf/include/param/commport.h
iconv -f GB2312 -t UTF-8 ./include/param/musictask.h          -o ../SmartHomeUtf/include/param/musictask.h
iconv -f GB2312 -t UTF-8 ./include/param/operation.h          -o ../SmartHomeUtf/include/param/operation.h
iconv -f GB2312 -t UTF-8 ./include/param/route.h              -o ../SmartHomeUtf/include/param/route.h
iconv -f GB2312 -t UTF-8 ./include/param/sceneuse.h           -o ../SmartHomeUtf/include/param/sceneuse.h
iconv -f GB2312 -t UTF-8 ./include/param/term.h               -o ../SmartHomeUtf/include/param/term.h
iconv -f GB2312 -t UTF-8 ./include/param/unique.h             -o ../SmartHomeUtf/include/param/unique.h
iconv -f GB2312 -t UTF-8 ./include/startarg.h                 -o ../SmartHomeUtf/include/startarg.h
iconv -f GB2312 -t UTF-8 ./include/sys/bin.h                  -o ../SmartHomeUtf/include/sys/bin.h
iconv -f GB2312 -t UTF-8 ./include/sys/cycsave.h              -o ../SmartHomeUtf/include/sys/cycsave.h
iconv -f GB2312 -t UTF-8 ./include/sys/diskspace.h            -o ../SmartHomeUtf/include/sys/diskspace.h
iconv -f GB2312 -t UTF-8 ./include/sys/event.h                -o ../SmartHomeUtf/include/sys/event.h
iconv -f GB2312 -t UTF-8 ./include/sys/file.h                 -o ../SmartHomeUtf/include/sys/file.h
iconv -f GB2312 -t UTF-8 ./include/sys/flat.h                 -o ../SmartHomeUtf/include/sys/flat.h
iconv -f GB2312 -t UTF-8 ./include/sys/gpio.h                 -o ../SmartHomeUtf/include/sys/gpio.h
iconv -f GB2312 -t UTF-8 ./include/sys/grpbin.h               -o ../SmartHomeUtf/include/sys/grpbin.h
iconv -f GB2312 -t UTF-8 ./include/sys/init.h                 -o ../SmartHomeUtf/include/sys/init.h
iconv -f GB2312 -t UTF-8 ./include/sys/mutex.h                -o ../SmartHomeUtf/include/sys/mutex.h
iconv -f GB2312 -t UTF-8 ./include/sys/reset.h                -o ../SmartHomeUtf/include/sys/reset.h
iconv -f GB2312 -t UTF-8 ./include/sys/rs485.h                -o ../SmartHomeUtf/include/sys/rs485.h
iconv -f GB2312 -t UTF-8 ./include/sys/schedule.h             -o ../SmartHomeUtf/include/sys/schedule.h
iconv -f GB2312 -t UTF-8 ./include/sys/sqlitedb.h             -o ../SmartHomeUtf/include/sys/sqlitedb.h
iconv -f GB2312 -t UTF-8 ./include/sys/syslock.h              -o ../SmartHomeUtf/include/sys/syslock.h
iconv -f GB2312 -t UTF-8 ./include/sys/task.h                 -o ../SmartHomeUtf/include/sys/task.h
iconv -f GB2312 -t UTF-8 ./include/sys/timeal.h               -o ../SmartHomeUtf/include/sys/timeal.h
iconv -f GB2312 -t UTF-8 ./include/sys/timer.h                -o ../SmartHomeUtf/include/sys/timer.h
iconv -f GB2312 -t UTF-8 ./include/sys/uart.h                 -o ../SmartHomeUtf/include/sys/uart.h
iconv -f GB2312 -t UTF-8 ./include/sys/xin.h                  -o ../SmartHomeUtf/include/sys/xin.h
iconv -f GB2312 -t UTF-8 ./include/uplink/svrnote.h           -o ../SmartHomeUtf/include/uplink/svrnote.h
iconv -f GB2312 -t UTF-8 ./include/version.h                  -o ../SmartHomeUtf/include/version.h
iconv -f GB2312 -t UTF-8 ./lib/bcd.c                          -o ../SmartHomeUtf/lib/bcd.c
iconv -f GB2312 -t UTF-8 ./lib/crc.c                          -o ../SmartHomeUtf/lib/crc.c
iconv -f GB2312 -t UTF-8 ./lib/datachg.c                      -o ../SmartHomeUtf/lib/datachg.c
iconv -f GB2312 -t UTF-8 ./lib/datatype_gb.c                  -o ../SmartHomeUtf/lib/datatype_gb.c
iconv -f GB2312 -t UTF-8 ./lib/dbtime.c                       -o ../SmartHomeUtf/lib/dbtime.c
iconv -f GB2312 -t UTF-8 ./lib/Makefile                       -o ../SmartHomeUtf/lib/Makefile
iconv -f GB2312 -t UTF-8 ./mail/codes.c                       -o ../SmartHomeUtf/mail/codes.c
iconv -f GB2312 -t UTF-8 ./mail/Makefile                      -o ../SmartHomeUtf/mail/Makefile
iconv -f GB2312 -t UTF-8 ./mail/md5.h                         -o ../SmartHomeUtf/mail/md5.h
iconv -f GB2312 -t UTF-8 ./mail/md5c.c                        -o ../SmartHomeUtf/mail/md5c.c
iconv -f GB2312 -t UTF-8 ./mail/ssmtp.c                       -o ../SmartHomeUtf/mail/ssmtp.c
iconv -f GB2312 -t UTF-8 ./mail/ssmtp.h                       -o ../SmartHomeUtf/mail/ssmtp.h
iconv -f GB2312 -t UTF-8 ./mail/testssmtp.c                   -o ../SmartHomeUtf/mail/testssmtp.c
iconv -f GB2312 -t UTF-8 ./mail/xmalloc.c                     -o ../SmartHomeUtf/mail/xmalloc.c
iconv -f GB2312 -t UTF-8 ./mail/xmalloc.h                     -o ../SmartHomeUtf/mail/xmalloc.h
iconv -f GB2312 -t UTF-8 ./main.c                             -o ../SmartHomeUtf/main.c
iconv -f GB2312 -t UTF-8 ./Makefile                           -o ../SmartHomeUtf/Makefile
iconv -f GB2312 -t UTF-8 ./monitor/alarm.c                    -o ../SmartHomeUtf/monitor/alarm.c
iconv -f GB2312 -t UTF-8 ./monitor/Makefile                   -o ../SmartHomeUtf/monitor/Makefile
iconv -f GB2312 -t UTF-8 ./monitor/monitor_init.c             -o ../SmartHomeUtf/monitor/monitor_init.c
iconv -f GB2312 -t UTF-8 ./monitor/monitor_task.c             -o ../SmartHomeUtf/monitor/monitor_task.c
iconv -f GB2312 -t UTF-8 ./monitor/netcheck.c                 -o ../SmartHomeUtf/monitor/netcheck.c
iconv -f GB2312 -t UTF-8 ./monitor/runstate.c                 -o ../SmartHomeUtf/monitor/runstate.c
iconv -f GB2312 -t UTF-8 ./param/Makefile                     -o ../SmartHomeUtf/param/Makefile
iconv -f GB2312 -t UTF-8 ./param/musictask.h                  -o ../SmartHomeUtf/param/musictask.h
iconv -f GB2312 -t UTF-8 ./param/operation.c                  -o ../SmartHomeUtf/param/operation.c
iconv -f GB2312 -t UTF-8 ./param/operation_inner.h            -o ../SmartHomeUtf/param/operation_inner.h
iconv -f GB2312 -t UTF-8 ./param/param_config.h               -o ../SmartHomeUtf/param/param_config.h
iconv -f GB2312 -t UTF-8 ./param/param_init.c                 -o ../SmartHomeUtf/param/param_init.c
iconv -f GB2312 -t UTF-8 ./param/sceneuse.c                   -o ../SmartHomeUtf/param/sceneuse.c
iconv -f GB2312 -t UTF-8 ./param/sqlitedb.c                   -o ../SmartHomeUtf/param/sqlitedb.c
iconv -f GB2312 -t UTF-8 ./param/term.c                       -o ../SmartHomeUtf/param/term.c
iconv -f GB2312 -t UTF-8 ./param/term.xin                     -o ../SmartHomeUtf/param/term.xin
iconv -f GB2312 -t UTF-8 ./param/unique.c                     -o ../SmartHomeUtf/param/unique.c
iconv -f GB2312 -t UTF-8 ./rules.mk                           -o ../SmartHomeUtf/rules.mk
iconv -f GB2312 -t UTF-8 ./save/itemop.c                      -o ../SmartHomeUtf/save/itemop.c
iconv -f GB2312 -t UTF-8 ./save/itemop.h                      -o ../SmartHomeUtf/save/itemop.h
iconv -f GB2312 -t UTF-8 ./save/Makefile                      -o ../SmartHomeUtf/save/Makefile
iconv -f GB2312 -t UTF-8 ./save/param.c                       -o ../SmartHomeUtf/save/param.c
iconv -f GB2312 -t UTF-8 ./save/param.h                       -o ../SmartHomeUtf/save/param.h
iconv -f GB2312 -t UTF-8 ./save/para_term.c                   -o ../SmartHomeUtf/save/para_term.c
iconv -f GB2312 -t UTF-8 ./save/para_term.h                   -o ../SmartHomeUtf/save/para_term.h
iconv -f GB2312 -t UTF-8 ./save/para_uni.c                    -o ../SmartHomeUtf/save/para_uni.c
iconv -f GB2312 -t UTF-8 ./save/para_uni.h                    -o ../SmartHomeUtf/save/para_uni.h
iconv -f GB2312 -t UTF-8 ./startarg.c                         -o ../SmartHomeUtf/startarg.c
iconv -f GB2312 -t UTF-8 ./startup.sh                         -o ../SmartHomeUtf/startup.sh
iconv -f GB2312 -t UTF-8 ./subdir.mk                          -o ../SmartHomeUtf/subdir.mk
iconv -f GB2312 -t UTF-8 ./svrcomm/faal.h                     -o ../SmartHomeUtf/svrcomm/faal.h
iconv -f GB2312 -t UTF-8 ./svrcomm/faal_dl.c                  -o ../SmartHomeUtf/svrcomm/faal_dl.c
iconv -f GB2312 -t UTF-8 ./svrcomm/faal_dl.h                  -o ../SmartHomeUtf/svrcomm/faal_dl.h
iconv -f GB2312 -t UTF-8 ./svrcomm/Makefile                   -o ../SmartHomeUtf/svrcomm/Makefile
iconv -f GB2312 -t UTF-8 ./sys/driver/driver_init.c           -o ../SmartHomeUtf/sys/driver/driver_init.c
iconv -f GB2312 -t UTF-8 ./sys/driver/gpio.c                  -o ../SmartHomeUtf/sys/driver/gpio.c
iconv -f GB2312 -t UTF-8 ./sys/driver/Makefile                -o ../SmartHomeUtf/sys/driver/Makefile
iconv -f GB2312 -t UTF-8 ./sys/driver/rs485.c                 -o ../SmartHomeUtf/sys/driver/rs485.c
iconv -f GB2312 -t UTF-8 ./sys/driver/uart.c                  -o ../SmartHomeUtf/sys/driver/uart.c
iconv -f GB2312 -t UTF-8 ./sys/Makefile                       -o ../SmartHomeUtf/sys/Makefile
iconv -f GB2312 -t UTF-8 ./sys/storage/bin.c                  -o ../SmartHomeUtf/sys/storage/bin.c
iconv -f GB2312 -t UTF-8 ./sys/storage/cycsave.c              -o ../SmartHomeUtf/sys/storage/cycsave.c
iconv -f GB2312 -t UTF-8 ./sys/storage/flat.c                 -o ../SmartHomeUtf/sys/storage/flat.c
iconv -f GB2312 -t UTF-8 ./sys/storage/grpbin.c               -o ../SmartHomeUtf/sys/storage/grpbin.c
iconv -f GB2312 -t UTF-8 ./sys/storage/Makefile               -o ../SmartHomeUtf/sys/storage/Makefile
iconv -f GB2312 -t UTF-8 ./sys/storage/mtd-abi.h              -o ../SmartHomeUtf/sys/storage/mtd-abi.h
iconv -f GB2312 -t UTF-8 ./sys/storage/storage_init.c         -o ../SmartHomeUtf/sys/storage/storage_init.c
iconv -f GB2312 -t UTF-8 ./sys/storage/xin.c                  -o ../SmartHomeUtf/sys/storage/xin.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/diskspace.c            -o ../SmartHomeUtf/sys/syscall/diskspace.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/event.c                -o ../SmartHomeUtf/sys/syscall/event.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/file.c                 -o ../SmartHomeUtf/sys/syscall/file.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/Makefile               -o ../SmartHomeUtf/sys/syscall/Makefile
iconv -f GB2312 -t UTF-8 ./sys/syscall/mem_alloc.c            -o ../SmartHomeUtf/sys/syscall/mem_alloc.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/reset.c                -o ../SmartHomeUtf/sys/syscall/reset.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/syscall_init.c         -o ../SmartHomeUtf/sys/syscall/syscall_init.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/syslock.c              -o ../SmartHomeUtf/sys/syscall/syslock.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/task.c                 -o ../SmartHomeUtf/sys/syscall/task.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/time.c                 -o ../SmartHomeUtf/sys/syscall/time.c
iconv -f GB2312 -t UTF-8 ./sys/syscall/timer.c                -o ../SmartHomeUtf/sys/syscall/timer.c
iconv -f GB2312 -t UTF-8 ./sys/sys_config.h                   -o ../SmartHomeUtf/sys/sys_config.h
iconv -f GB2312 -t UTF-8 ./sys/sys_init.c                     -o ../SmartHomeUtf/sys/sys_init.c
iconv -f GB2312 -t UTF-8 ./test.rtf                           -o ../SmartHomeUtf/test.rtf
iconv -f GB2312 -t UTF-8 ./uplink/ether.c                     -o ../SmartHomeUtf/uplink/ether.c
iconv -f GB2312 -t UTF-8 ./uplink/ethsvr.c                    -o ../SmartHomeUtf/uplink/ethsvr.c
iconv -f GB2312 -t UTF-8 ./uplink/keepalive.c                 -o ../SmartHomeUtf/uplink/keepalive.c
iconv -f GB2312 -t UTF-8 ./uplink/keepalive.h                 -o ../SmartHomeUtf/uplink/keepalive.h
iconv -f GB2312 -t UTF-8 ./uplink/localsvr.c                  -o ../SmartHomeUtf/uplink/localsvr.c
iconv -f GB2312 -t UTF-8 ./uplink/Makefile                    -o ../SmartHomeUtf/uplink/Makefile
iconv -f GB2312 -t UTF-8 ./uplink/serial.c                    -o ../SmartHomeUtf/uplink/serial.c
iconv -f GB2312 -t UTF-8 ./uplink/smspost.c                   -o ../SmartHomeUtf/uplink/smspost.c
iconv -f GB2312 -t UTF-8 ./uplink/sms_tcpclient.c             -o ../SmartHomeUtf/uplink/sms_tcpclient.c
iconv -f GB2312 -t UTF-8 ./uplink/sms_tcpclient.h             -o ../SmartHomeUtf/uplink/sms_tcpclient.h
iconv -f GB2312 -t UTF-8 ./uplink/svrcomm.c                   -o ../SmartHomeUtf/uplink/svrcomm.c
iconv -f GB2312 -t UTF-8 ./uplink/svrcomm.h                   -o ../SmartHomeUtf/uplink/svrcomm.h
iconv -f GB2312 -t UTF-8 ./uplink/svrmsg.c                    -o ../SmartHomeUtf/uplink/svrmsg.c
iconv -f GB2312 -t UTF-8 ./uplink/tcpsvr.c                    -o ../SmartHomeUtf/uplink/tcpsvr.c
iconv -f GB2312 -t UTF-8 ./uplink/uplink_buffer.c             -o ../SmartHomeUtf/uplink/uplink_buffer.c
iconv -f GB2312 -t UTF-8 ./uplink/uplink_dl.c                 -o ../SmartHomeUtf/uplink/uplink_dl.c
iconv -f GB2312 -t UTF-8 ./uplink/uplink_dl.h                 -o ../SmartHomeUtf/uplink/uplink_dl.h
iconv -f GB2312 -t UTF-8 ./uplink/uplink_pkt.h                -o ../SmartHomeUtf/uplink/uplink_pkt.h
iconv -f GB2312 -t UTF-8 ./utils/mkdate.c                     -o ../SmartHomeUtf/utils/mkdate.c
iconv -f GB2312 -t UTF-8 ./utils/testdll.c                    -o ../SmartHomeUtf/utils/testdll.c
iconv -f GB2312 -t UTF-8 ./utils/xzip.c                       -o ../SmartHomeUtf/utils/xzip.c
iconv -f GB2312 -t UTF-8 ./version.c                          -o ../SmartHomeUtf/version.c
cp ./utils/xzip ../SmartHomeUtf/utils/
cp ./utils/mkdate ../SmartHomeUtf/utils/