#!/bin/sh
cd /opt/

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#

mount -a
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
mkdir -p /var/lock

mkdir /dev/fb /dev/v4l
ln -s /dev/fb0 /dev/fb/0
ln -s /dev/video0 /dev/v4l/video0

hwclock -s
EmbedSky_wdg &

insmod /lib/modules/mac80211.ko
#TL-WN321G+
#insmod /lib/modules/rt2x00lib.ko
#insmod /lib/modules/rt2x00usb.ko
#insmod /lib/modules/rt73usb.ko
#TL-WN322G+
#insmod /lib/modules/zd1211rw.ko

#ifconfig lo 127.0.0.1
net_set &

syslogd
/etc/rc.d/init.d/netd start

sleep 1
/etc/rc.d/init.d/httpd start

/bin/hostname -F /etc/sysconfig/HOSTNAME

/work/startup.sh
echo "/etc/init.d/rcS done."
/bin/sh


