mkdir -p ../SmartHomeUtf/debug
mkdir -p ../SmartHomeUtf/downlink
mkdir -p ../SmartHomeUtf/downlink/module
mkdir -p ../SmartHomeUtf/include
mkdir -p ../SmartHomeUtf/include/debug
mkdir -p ../SmartHomeUtf/include/lib
mkdir -p ../SmartHomeUtf/include/monitor
mkdir -p ../SmartHomeUtf/include/param
mkdir -p ../SmartHomeUtf/include/sys
mkdir -p ../SmartHomeUtf/include/uplink
mkdir -p ../SmartHomeUtf/lib
mkdir -p ../SmartHomeUtf/mail
mkdir -p ../SmartHomeUtf/monitor
mkdir -p ../SmartHomeUtf/param
mkdir -p ../SmartHomeUtf/save
mkdir -p ../SmartHomeUtf/svrcomm
mkdir -p ../SmartHomeUtf/sys
mkdir -p ../SmartHomeUtf/sys/driver
mkdir -p ../SmartHomeUtf/sys/storage
mkdir -p ../SmartHomeUtf/sys/syscall
mkdir -p ../SmartHomeUtf/uplink
mkdir -p ../SmartHomeUtf/utils
